# Generated by Django 3.2 on 2021-05-10 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='School',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='blog.school'),
            preserve_default=False,
        ),
    ]
